<a href="https://colab.research.google.com/github/Kuo2022/20220702-python/blob/main/20220716.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##20220709作業參考解答
api網址：https://www.moedict.tw/a/%E8%90%8C.json

In [ ]:
!pip install gradio

In [ ]:
import requests

In [ ]:
def lookup(word):
  url = "https://www.moedict.tw/a/"
  data = requests.get(url + word+ ".json").json()
  return data['English']

In [ ]:
lookup("教室")

'classroom'

In [ ]:
import gradio

In [ ]:
gradio.Interface(lookup, "text", "text", title="漢英字典").launch(share=True)

Colab notebook detected. To show errors in colab notebook, set `debug=True` in `launch()`
Running on public URL: https://16366.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces (https://huggingface.co/spaces)


(<gradio.routes.App at 0x7f4503871f90>,
 'http://127.0.0.1:7860/',
 'https://16366.gradio.app')

## 註冊 ZeroJudge

https://zerojudge.tw/

解解看底下題目：
* https://zerojudge.tw/ShowProblem?problemid=a002
* https://zerojudge.tw/ShowProblem?problemid=a003

## 基本語法

* 迴圈 (loops) => for, while
* 函式 (functions)
* 條件式 (if statements)
* 例外處理 (Exception Handling) 

### 例外處理

In [16]:
def add(x, y):
  print(f"{x} + {y} = {x + y}")

def sub(x, y):
  print(f"{x} - {y} = {x - y}")

def mul(x, y):
  print(f"{x} x {y} = {x * y}")

def div(x, y):
  print(f"{x} / {y} = {x / y}")

In [17]:
functions = [add, div, mul, sub]

In [18]:
add(2, 1)

2 + 1 = 3


In [19]:
x = 4
y = 2
for func in functions:
  func(x, y)

4 + 2 = 6
4 / 2 = 2.0
4 x 2 = 8
4 - 2 = 2


In [20]:
#錯誤算式-除法有誤，後面2個算式就不執行了。
x = 4
y = 0
for func in functions:
  func(x, y)

4 + 0 = 4


ZeroDivisionError: ignored

In [21]:
#例外處理的語法
x = 4
y = 0
for func in functions:
  try:
    func(x, y)
  except Exception as e:
    print(e.args)

4 + 0 = 4
('division by zero',)
4 x 0 = 0
4 - 0 = 4


## 資料分析簡介
* Numpy
  * Numerical Python
  * 科學運算基礎套件
* MatPlotLib
  * Matrix Plotting Library
  * 繪圖基礎套件
* Pandas
  * Panel Data
  * 資料分析基礎套件

```python
import numpy as np【別名】
import matplotlib.pyplot as plt
import pandas as pd
```

## Numpy

* new data type
  * ndarray => Multi-Dimentional Array
* new functions to process data
  * ufunc => Universal Functions

## 使用原生的Python執行向量運算時會遇到的問題

In [ ]:
x1 = [1, 2, 3]
x2 = [4, 5, 6]

In [ ]:
#向量相加 下列算式是錯誤的
x1 + x2

[1, 2, 3, 4, 5, 6]

In [ ]:
#向量乘法 下列算式是錯誤的
2*x1

[1, 2, 3, 1, 2, 3]

In [15]:
#向量運算
x3 = []
for i, j in zip(x1, x2):
  x3.append(i + j)

## Numpy 用來做什麼？

ndarray ==> 多維陣列

In [22]:
import numpy as np

In [23]:
x1

[1, 2, 3]

In [24]:
x2

[4, 5, 6]

In [25]:
y1 = np.array(x1)
y2 = np.array(x2)

In [26]:
y1 + y2

array([5, 7, 9])

In [27]:
2 * y1

array([2, 4, 6])

ufunc ==> 通用函式

In [28]:
# 在原生的python中
import math

In [29]:
math.sin(math.pi/2)

1.0

In [35]:
math.sin(x1)

TypeError: ignored

In [31]:
# 在 numpy 中
np.sin(np.pi/2)

1.0

In [36]:
np.sin(x1)

array([0.84147098, 0.90929743, 0.14112001])

### 什麼地方會用到ndarray?【看影片】

In [44]:
import cv2

In [45]:
im = cv2.imread("lin.jpg")

In [ ]:
type(im)

In [ ]:
im.shape

In [41]:
import matplotlib.pyplot as plt

In [ ]:
plt.imshow(im)

# 如何用Python畫地圖

LBS: Location-Based Service
Folium快速入門:

https://python-visualization.github.io/folium/quickstart.html

In [47]:
import folium

m = folium.Map(location=[45.5236, -122.6750])

In [ ]:
m

In [53]:
m = folium.Map(location=[22.6273, 120.3014],zoom_start=16)

In [54]:
m

In [55]:
#存成網頁
m.save("index.html")

In [56]:
m = folium.Map(location=[22.6273, 120.3014],zoom_start=16)
folium.Marker([22.6273, 120.3014], popup="高雄市").add_to(m)
m

##使用geocoder查詢GPS座標
https://geocoder.readthedocs.io/

In [ ]:
!pip install geocoder

In [58]:
import geocoder

In [59]:
geocoder.osm("台北市").latlng

[25.0375198, 121.5636796]

## 練習:請使用 geocoder + folium 畫出台北市地圖

In [60]:
m = folium.Map(location=[25.0375198, 121.5636796],zoom_start=16)
folium.Marker([25.0375198, 121.5636796], popup="台北市").add_to(m)
m

In [61]:
geocoder.osm("澄清湖").latlng

[22.660662549999998, 120.35109204721456]

In [62]:
m = folium.Map(location=[22.660662549999998, 120.35109204721456],zoom_start=16)
folium.Marker([22.660662549999998, 120.35109204721456], popup="澄清湖").add_to(m)
m