<a href="https://colab.research.google.com/github/Kuo2022/20220702-python/blob/main/20220723.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 複習一下套件載入慣用法

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

## NumPy

* ndarray
* ufunc

## ndarray

* indexing
* slicing

In [1]:
import numpy as np

In [2]:
data = np.arange(25)

In [3]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

##檢查ndarray的屬性

In [6]:
data.dtype?

In [7]:
data.dtype

dtype('int64')

In [8]:
data.size

25

In [9]:
data.shape

(25,)

##改變ndarray的形狀

In [10]:
data.reshape?

In [12]:
data.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
# overwrite original data
data = data.reshape(5, 5)

In [15]:
data1 = [[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]]

In [16]:
len(data1)

5

In [17]:
data1[2]

[10, 11, 12, 13, 14]

In [18]:
data1[1][2]

7

In [19]:
data[2]

array([10, 11, 12, 13, 14])

In [20]:
data1[1:3]

[[5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [23]:
data[1:3][1:3]

array([[10, 11, 12, 13, 14]])

In [24]:
data[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [25]:
data[1, 2]

7

In [26]:
data[1, 1:3]

array([6, 7])

In [27]:
data[0]

array([0, 1, 2, 3, 4])

In [28]:
data[0, :]

array([0, 1, 2, 3, 4])